[package]
name = "mhtame"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsz_macros = { path = "./rsz_macros" }
byteorder = "1.5.0"
clap = { version = "4.5.20", features = ["derive"] }
image = "0.25.5"
once_cell = "1.5"
serde = { version = "1.0", features = ["rc"] }
serde_derive = { version =">=1.0.188"}
serde_json = {version = "1.0", features = ["preserve_order"]}
bitflags = "2"
nalgebra-glm = { version = "0.19", features = ["serde-serialize"]}
nalgebra = "*"
uuid = "1.11.0"
libdeflater = {git = "https://github.com/c-ola/libdeflater.git", branch = "master" }
indexmap = { version = "2.7.0", features = ["serde"] }
quote = "1.0.40"
syn = "2.0.100"
proc-macro2 = "1.0.94"
log = "0.4.27"
env_logger = "0.11.8"
#libdeflater = {path = "/home/nikola/programming/libdeflater"}
